version: 2

    
# https://nbsphinx.readthedocs.io/en/0.8.0/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org
python:
  version: 3
  install:
    - requirements: docs/requirements.txt
  system_packages: true