version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    
# https://nbsphinx.readthedocs.io/en/0.8.0/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org
python:
  install:
    - requirements: docs/requirements.txt
  system_packages: true